#Build image
FROM ubuntu:18.04 as build-step

RUN apt-get -y update
RUN apt-get -y install curl autoconf automake cmake libbz2-dev libace-dev libssl-dev libmysqlclient-dev libtool build-essential

COPY . /mangoserver
RUN mkdir /mangoserver/build
WORKDIR /mangoserver/build

#Install mangos
RUN cmake .. -DCMAKE_INSTALL_PREFIX=/mangos -DBUILD_MANGOSD=1 -DBUILD_REALMD=0 -DBUILD_TOOLS=0
RUN make -j4
RUN make install

#Runtime image
FROM alpine:3.10

COPY --from=build-step /mangos /mangos
WORKDIR /mangos /mangos
RUN cp ./etc/mangosd.conf.dist ./etc/mangosd.conf

EXPOSE 8085
ENTRYPOINT [ "mangosd", "-c", "./etc/mangosd.conf" ]
