FROM mysql:5.6

RUN apt-get -y update
RUN apt-get -y install git

RUN mkdir /mangodb
WORKDIR /mangodb

RUN git clone https://github.com/mangostwo/database.git --recursive --depth 1

RUN chmod -R +x *.sh

ENTRYPOINT "./InstallDatabases.sh && ./make_full_WorldDB.sh && mysql"