#ifndef DBCSTRUCTURE_REFERENCE_H
#define DBCSTRUCTURE_REFERENCE_H

// AUTO-GENERATED by CoreAlign/tools/gen_reference.py -- DO NOT EDIT.
// Inert reference map of the WotLK 3.3.5.12340 client DBC tables the core does NOT load.
// This header is never #included; activating a table = move its struct into
// DBCStructure.h, add its fmt to DBCfmt.h, and a DBCStorage loader.

/*
 * DBC MAP -- 245 client WotLK tables (build 3.3.5.12340)
 *   ACTIVE = modelled + loaded by the core ; DOC = inert reference struct below.
 *   Derived from the live LoadDBC calls in DBCStores.cpp.
 *
 *   Achievement                    ACTIVE
 *   Achievement_Category           ACTIVE
 *   Achievement_Criteria           ACTIVE
 *   AnimationData                  DOC   (8 cols)
 *   AreaGroup                      ACTIVE
 *   AreaPOI                        DOC   (54 cols)
 *   AreaTable                      ACTIVE
 *   AreaTrigger                    ACTIVE
 *   AttackAnimKits                 DOC   (5 cols)
 *   AttackAnimTypes                DOC   (2 cols)
 *   AuctionHouse                   ACTIVE
 *   BankBagSlotPrices              ACTIVE
 *   BannedAddOns                   DOC   (11 cols)
 *   BarberShopStyle                ACTIVE
 *   BattlemasterList               ACTIVE
 *   CameraShakes                   DOC   (8 cols)
 *   Cfg_Categories                 DOC   (21 cols)
 *   Cfg_Configs                    DOC   (4 cols)
 *   CharBaseInfo                   DOC   (2 cols)
 *   CharHairGeosets                DOC   (6 cols)
 *   CharHairTextures               DOC   (8 cols)
 *   CharSections                   DOC   (10 cols)
 *   CharStartOutfit                ACTIVE
 *   CharTitles                     ACTIVE
 *   CharacterFacialHairStyles      DOC   (8 cols)
 *   ChatChannels                   ACTIVE
 *   ChatProfanity                  DOC   (3 cols)
 *   ChrClasses                     ACTIVE
 *   ChrRaces                       ACTIVE
 *   CinematicCamera                DOC   (7 cols)
 *   CinematicSequences             ACTIVE
 *   CreatureDisplayInfo            ACTIVE
 *   CreatureDisplayInfoExtra       ACTIVE
 *   CreatureFamily                 ACTIVE
 *   CreatureModelData              ACTIVE
 *   CreatureMovementInfo           DOC   (2 cols)
 *   CreatureSoundData              DOC   (38 cols)
 *   CreatureSpellData              ACTIVE
 *   CreatureType                   ACTIVE
 *   CurrencyCategory               ACTIVE
 *   CurrencyTypes                  ACTIVE
 *   DanceMoves                     DOC   (24 cols)
 *   DeathThudLookups               DOC   (5 cols)
 *   DeclinedWord                   DOC   (2 cols)
 *   DeclinedWordCases              DOC   (4 cols)
 *   DestructibleModelData          ACTIVE
 *   DungeonEncounter               ACTIVE
 *   DungeonMap                     DOC   (8 cols)
 *   DungeonMapChunk                DOC   (5 cols)
 *   DurabilityCosts                ACTIVE
 *   DurabilityQuality              ACTIVE
 *   Emotes                         ACTIVE
 *   EmotesText                     ACTIVE
 *   EmotesTextData                 DOC   (18 cols)
 *   EmotesTextSound                DOC   (5 cols)
 *   EnvironmentalDamage            DOC   (3 cols)
 *   Exhaustion                     DOC   (23 cols)
 *   Faction                        ACTIVE
 *   FactionGroup                   DOC   (20 cols)
 *   FactionTemplate                ACTIVE
 *   FileData                       DOC   (3 cols)
 *   FootprintTextures              DOC   (2 cols)
 *   FootstepTerrainLookup          DOC   (5 cols)
 *   GMSurveyAnswers                DOC   (20 cols)
 *   GMSurveyCurrentSurvey          DOC   (2 cols)
 *   GMSurveyQuestions              DOC   (18 cols)
 *   GMSurveySurveys                DOC   (11 cols)
 *   GMTicketCategory               DOC   (18 cols)
 *   GameObjectArtKit               DOC   (8 cols)
 *   GameObjectDisplayInfo          ACTIVE
 *   GameTables                     DOC   (3 cols)
 *   GameTips                       DOC   (18 cols)
 *   GemProperties                  ACTIVE
 *   GlyphProperties                ACTIVE
 *   GlyphSlot                      ACTIVE
 *   GroundEffectDoodad             DOC   (3 cols)
 *   GroundEffectTexture            DOC   (11 cols)
 *   HelmetGeosetVisData            DOC   (8 cols)
 *   HolidayDescriptions            DOC   (18 cols)
 *   HolidayNames                   ACTIVE
 *   Holidays                       ACTIVE
 *   Item                           ACTIVE
 *   ItemBagFamily                  ACTIVE
 *   ItemClass                      ACTIVE
 *   ItemCondExtCosts               DOC   (4 cols)  [phantom: commented fmt]
 *   ItemDisplayInfo                ACTIVE
 *   ItemExtendedCost               ACTIVE
 *   ItemGroupSounds                DOC   (5 cols)
 *   ItemLimitCategory              ACTIVE
 *   ItemPetFood                    DOC   (18 cols)
 *   ItemPurchaseGroup              DOC   (26 cols)
 *   ItemRandomProperties           ACTIVE
 *   ItemRandomSuffix               ACTIVE
 *   ItemSet                        ACTIVE
 *   ItemSubClass                   DOC   (44 cols)
 *   ItemSubClassMask               DOC   (19 cols)
 *   ItemVisualEffects              DOC   (2 cols)
 *   ItemVisuals                    DOC   (6 cols)
 *   LFGDungeonExpansion            DOC   (8 cols)
 *   LFGDungeonGroup                DOC   (21 cols)
 *   LFGDungeons                    ACTIVE
 *   LanguageWords                  DOC   (3 cols)
 *   Languages                      DOC   (18 cols)
 *   Light                          DOC   (15 cols)
 *   LightFloatBand                 DOC   (34 cols)
 *   LightIntBand                   DOC   (34 cols)
 *   LightParams                    DOC   (9 cols)
 *   LightSkybox                    DOC   (3 cols)
 *   LiquidMaterial                 DOC   (3 cols)
 *   LiquidType                     ACTIVE
 *   LoadingScreenTaxiSplines       DOC   (19 cols)
 *   LoadingScreens                 DOC   (4 cols)
 *   Lock                           ACTIVE
 *   LockType                       DOC   (53 cols)
 *   MailTemplate                   ACTIVE
 *   Map                            ACTIVE
 *   MapDifficulty                  ACTIVE
 *   Material                       DOC   (5 cols)
 *   Movie                          ACTIVE
 *   MovieFileData                  DOC   (2 cols)
 *   MovieVariation                 DOC   (3 cols)
 *   NPCSounds                      DOC   (5 cols)
 *   NameGen                        DOC   (4 cols)
 *   NamesProfanity                 DOC   (3 cols)
 *   NamesReserved                  DOC   (3 cols)
 *   ObjectEffect                   DOC   (12 cols)
 *   ObjectEffectGroup              DOC   (2 cols)
 *   ObjectEffectModifier           DOC   (8 cols)
 *   ObjectEffectPackage            DOC   (2 cols)
 *   ObjectEffectPackageElem        DOC   (4 cols)
 *   OverrideSpellData              ACTIVE
 *   Package                        DOC   (20 cols)
 *   PageTextMaterial               DOC   (2 cols)
 *   PaperDollItemFrame             DOC   (3 cols)
 *   ParticleColor                  DOC   (10 cols)
 *   PetPersonality                 DOC   (24 cols)
 *   PetitionType                   DOC   (3 cols)
 *   PowerDisplay                   ACTIVE
 *   PvpDifficulty                  ACTIVE
 *   QuestFactionReward             ACTIVE
 *   QuestInfo                      DOC   (18 cols)
 *   QuestSort                      ACTIVE
 *   QuestXP                        ACTIVE
 *   RandPropPoints                 ACTIVE
 *   Resistances                    DOC   (20 cols)
 *   ScalingStatDistribution        ACTIVE
 *   ScalingStatValues              ACTIVE
 *   ScreenEffect                   DOC   (10 cols)
 *   ServerMessages                 DOC   (18 cols)
 *   SheatheSoundLookups            DOC   (7 cols)
 *   SkillCostsData                 DOC   (5 cols)
 *   SkillLine                      ACTIVE
 *   SkillLineAbility               ACTIVE
 *   SkillLineCategory              DOC   (19 cols)
 *   SkillRaceClassInfo             ACTIVE
 *   SkillTiers                     DOC   (33 cols)
 *   SoundAmbience                  DOC   (3 cols)
 *   SoundEmitters                  DOC   (10 cols)
 *   SoundEntries                   ACTIVE
 *   SoundEntriesAdvanced           DOC   (24 cols)
 *   SoundFilter                    DOC   (2 cols)
 *   SoundFilterElem                DOC   (13 cols)
 *   SoundProviderPreferences       DOC   (24 cols)
 *   SoundSamplePreferences         DOC   (17 cols)
 *   SoundWaterType                 DOC   (4 cols)
 *   SpamMessages                   DOC   (2 cols)
 *   Spell                          ACTIVE
 *   SpellCastTimes                 ACTIVE
 *   SpellCategory                  DOC   (2 cols)
 *   SpellChainEffects              DOC   (48 cols)
 *   SpellDescriptionVariables      DOC   (2 cols)
 *   SpellDifficulty                ACTIVE
 *   SpellDispelType                DOC   (21 cols)
 *   SpellDuration                  ACTIVE
 *   SpellEffectCameraShakes        DOC   (4 cols)
 *   SpellFocusObject               ACTIVE
 *   SpellIcon                      DOC   (2 cols)
 *   SpellItemEnchantment           ACTIVE
 *   SpellItemEnchantmentCondition  ACTIVE
 *   SpellMechanic                  DOC   (18 cols)
 *   SpellMissile                   DOC   (15 cols)
 *   SpellMissileMotion             DOC   (5 cols)
 *   SpellRadius                    ACTIVE
 *   SpellRange                     ACTIVE
 *   SpellRuneCost                  ACTIVE
 *   SpellShapeshiftForm            ACTIVE
 *   SpellVisual                    DOC   (32 cols)
 *   SpellVisualEffectName          DOC   (7 cols)
 *   SpellVisualKit                 DOC   (38 cols)
 *   SpellVisualKitAreaModel        DOC   (3 cols)
 *   SpellVisualKitModelAttach      DOC   (10 cols)
 *   SpellVisualPrecastTransitions  DOC   (3 cols)
 *   StableSlotPrices               ACTIVE
 *   Startup_Strings                DOC   (19 cols)
 *   Stationery                     DOC   (4 cols)
 *   StringLookups                  DOC   (2 cols)
 *   SummonProperties               ACTIVE
 *   Talent                         ACTIVE
 *   TalentTab                      ACTIVE
 *   TaxiNodes                      ACTIVE
 *   TaxiPath                       ACTIVE
 *   TaxiPathNode                   ACTIVE
 *   TeamContributionPoints         ACTIVE
 *   TerrainType                    DOC   (6 cols)
 *   TerrainTypeSounds              DOC   (1 cols)
 *   TotemCategory                  ACTIVE
 *   TransportAnimation             DOC   (7 cols)
 *   TransportPhysics               DOC   (11 cols)
 *   TransportRotation              DOC   (7 cols)
 *   UISoundLookups                 DOC   (3 cols)
 *   UnitBlood                      DOC   (10 cols)
 *   UnitBloodLevels                DOC   (4 cols)
 *   Vehicle                        ACTIVE
 *   VehicleSeat                    ACTIVE
 *   VehicleUIIndSeat               DOC   (5 cols)
 *   VehicleUIIndicator             DOC   (2 cols)
 *   VideoHardware                  DOC   (23 cols)
 *   VocalUISounds                  DOC   (7 cols)
 *   WMOAreaTable                   ACTIVE
 *   WeaponImpactSounds             DOC   (23 cols)
 *   WeaponSwingSounds2             DOC   (4 cols)
 *   Weather                        DOC   (8 cols)
 *   WorldChunkSounds               DOC   (9 cols)
 *   WorldMapArea                   ACTIVE
 *   WorldMapContinent              DOC   (14 cols)
 *   WorldMapOverlay                ACTIVE
 *   WorldMapTransforms             DOC   (10 cols)
 *   WorldSafeLocs                  ACTIVE
 *   WorldStateUI                   DOC   (63 cols)
 *   WorldStateZoneSounds           DOC   (8 cols)
 *   WowError_Strings               DOC   (19 cols)
 *   ZoneIntroMusicTable            DOC   (5 cols)
 *   ZoneMusic                      DOC   (8 cols)
 *   gtBarberShopCostBase           ACTIVE
 *   gtChanceToMeleeCrit            ACTIVE
 *   gtChanceToMeleeCritBase        ACTIVE
 *   gtChanceToSpellCrit            ACTIVE
 *   gtChanceToSpellCritBase        ACTIVE
 *   gtCombatRatings                ACTIVE
 *   gtNPCManaCostScaler            DOC   (1 cols)
 *   gtOCTClassCombatRatingScalar   ACTIVE
 *   gtOCTRegenHP                   ACTIVE
 *   gtOCTRegenMP                   DOC   (1 cols)  [phantom: commented fmt]
 *   gtRegenHPPerSpt                ACTIVE
 *   gtRegenMPPerSpt                ACTIVE
 *
 *   (103 ACTIVE, 142 DOC)  phantoms: ItemCondExtCosts, gtOCTRegenMP
 */

// AnimationData -- 8 cols, record_size 32, build 3.3.5.12340. INERT reference (not loaded).
struct AnimationDataEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    uint32  Weaponflags;  // 2
    uint32  Bodyflags;  // 3
    uint32  Flags;  // 4
    int32   Fallback;  // 5
    int32   BehaviorID;  // 6
    int32   BehaviorTier;  // 7
};

// AreaPOI -- 54 cols, record_size 216, build 3.3.5.12340. INERT reference (not loaded).
struct AreaPOIEntry
{
    uint32  ID;  // 0
    int32   Importance;  // 1
    uint32  Icon[9];  // 2-10
    uint32  FactionID;  // 11
    float   Pos[3];  // 12-14
    uint32  ContinentID;  // 15
    uint32  Flags;  // 16
    uint32  AreaID;  // 17
    char*   Name_lang[16];  // 18-33
// uint32  Name_lang_flags;  // 34
    char*   Description_lang[16];  // 35-50
// uint32  Description_lang_flags;  // 51
    uint32  WorldStateID;  // 52
    uint32  WorldMapLink;  // 53
};

// AttackAnimKits -- 5 cols, record_size 20, build 3.3.5.12340. INERT reference (not loaded).
struct AttackAnimKitsEntry
{
    uint32  ID;  // 0
    uint32  ItemSubclassID;  // 1
    uint32  AnimTypeID;  // 2
    uint32  AnimFrequency;  // 3
    uint32  WhichHand;  // 4
};

// AttackAnimTypes -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct AttackAnimTypesEntry
{
    uint32  AnimID;  // 0
    char*   AnimName;  // 1
};

// BannedAddOns -- 11 cols, record_size 44, build 3.3.5.12340. INERT reference (not loaded).
struct BannedAddOnsEntry
{
    uint32  ID;  // 0
    uint32  NameMD5[4];  // 1-4
    uint32  VersionMD5[4];  // 5-8
    uint32  LastModified;  // 9
    uint32  Flags;  // 10
};

// CameraShakes -- 8 cols, record_size 32, build 3.3.5.12340. INERT reference (not loaded).
struct CameraShakesEntry
{
    int32   ID;  // 0
    int32   ShakeType;  // 1
    int32   Direction;  // 2
    float   Amplitude;  // 3
    float   Frequency;  // 4
    float   Duration;  // 5
    float   Phase;  // 6
    float   Coefficient;  // 7
};

// Cfg_Categories -- 21 cols, record_size 84, build 3.3.5.12340. INERT reference (not loaded).
struct Cfg_CategoriesEntry
{
    uint32  ID;  // 0
    uint32  LocaleMask;  // 1
    uint32  CreateCharsetMask;  // 2
    uint32  Flags;  // 3
    char*   Name_lang[16];  // 4-19
// uint32  Name_lang_flags;  // 20
};

// Cfg_Configs -- 4 cols, record_size 16, build 3.3.5.12340. INERT reference (not loaded).
struct Cfg_ConfigsEntry
{
    uint32  ID;  // 0
    uint32  RealmType;  // 1
    uint32  PlayerKillingAllowed;  // 2
    uint32  Roleplaying;  // 3
};

// CharBaseInfo -- 2 cols, record_size 2, build 3.3.5.12340. INERT reference (not loaded).
struct CharBaseInfoEntry
{
    int8    RaceID;  // 0
    int8    ClassID;  // 1
};

// CharHairGeosets -- 6 cols, record_size 24, build 3.3.5.12340. INERT reference (not loaded).
struct CharHairGeosetsEntry
{
    int32   ID;  // 0
    int32   RaceID;  // 1
    int32   SexID;  // 2
    int32   VariationID;  // 3
    int32   GeosetID;  // 4
    int32   Showscalp;  // 5
};

// CharHairTextures -- 8 cols, record_size 32, build 3.3.5.12340. INERT reference (not loaded).
struct CharHairTexturesEntry
{
    int32   ID;  // [dbd-only] 0
    int32   RaceID;  // [dbd-only] 1
    int32   Gender;  // [dbd-only] 2
    int32   Field03;  // [dbd-only] 3
    int32   MaybeRaceMask;  // [dbd-only] 4
    int32   Variation;  // [dbd-only] 5
    int32   Field06;  // [dbd-only] 6
    int32   Field07;  // [dbd-only] 7
};

// CharSections -- 10 cols, record_size 40, build 3.3.5.12340. INERT reference (not loaded).
struct CharSectionsEntry
{
    uint32  ID;  // 0
    uint32  RaceID;  // 1
    uint32  SexID;  // 2
    uint32  BaseSection;  // 3
    char*   TextureName[3];  // 4-6
    uint32  Flags;  // 7
    uint32  VariationIndex;  // 8
    uint32  ColorIndex;  // 9
};

// CharacterFacialHairStyles -- 8 cols, record_size 32, build 3.3.5.12340. INERT reference (not loaded).
struct CharacterFacialHairStylesEntry
{
    uint32  RaceID;  // 0
    uint32  SexID;  // 1
    uint32  VariationID;  // 2
    uint32  Geoset[5];  // 3-7
};

// ChatProfanity -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct ChatProfanityEntry
{
    int32   ID;  // 0
    char*   Text;  // 1
    int32   Language;  // 2
};

// CinematicCamera -- 7 cols, record_size 28, build 3.3.5.12340. INERT reference (not loaded).
struct CinematicCameraEntry
{
    uint32  ID;  // 0
    char*   Model;  // 1
    uint32  SoundID;  // 2
    float   OriginX;  // 3
    float   OriginY;  // 4
    float   OriginZ;  // 5
    float   OriginFacing;  // 6
};

// CreatureMovementInfo -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct CreatureMovementInfoEntry
{
    uint32  ID;  // 0
    float   SmoothFacingChaseRate;  // 1
};

// CreatureSoundData -- 38 cols, record_size 152, build 3.3.5.12340. INERT reference (not loaded).
struct CreatureSoundDataEntry
{
    uint32  ID;  // 0
    uint32  SoundExertionID;  // 1
    uint32  SoundExertionCriticalID;  // 2
    uint32  SoundInjuryID;  // 3
    uint32  SoundInjuryCriticalID;  // 4
    uint32  SoundInjuryCrushingBlowID;  // 5
    uint32  SoundDeathID;  // 6
    uint32  SoundStunID;  // 7
    uint32  SoundStandID;  // 8
    uint32  SoundFootstepID;  // 9
    uint32  SoundAggroID;  // 10
    uint32  SoundWingFlapID;  // 11
    uint32  SoundWingGlideID;  // 12
    uint32  SoundAlertID;  // 13
    uint32  SoundFidget[5];  // 14-18
    uint32  CustomAttack[4];  // 19-22
    uint32  NPCSoundID;  // 23
    uint32  LoopSoundID;  // 24
    uint32  CreatureImpactType;  // 25
    uint32  SoundJumpStartID;  // 26
    uint32  SoundJumpEndID;  // 27
    uint32  SoundPetAttackID;  // 28
    uint32  SoundPetOrderID;  // 29
    uint32  SoundPetDismissID;  // 30
    float   FidgetDelaySecondsMin;  // 31
    float   FidgetDelaySecondsMax;  // 32
    uint32  BirthSoundID;  // 33
    uint32  SpellCastDirectedSoundID;  // 34
    uint32  SubmergeSoundID;  // 35
    uint32  SubmergedSoundID;  // 36
    uint32  CreatureSoundDataIDPet;  // 37
};

// DanceMoves -- 24 cols, record_size 96, build 3.3.5.12340. INERT reference (not loaded).
struct DanceMovesEntry
{
    uint32  ID;  // 0
    int32   Type;  // 1
    int32   Param;  // 2
    int32   Fallback;  // 3
    uint32  Racemask;  // 4
    char*   Internal_name;  // 5
    char*   Name_lang[16];  // 6-21
// uint32  Name_lang_flags;  // 22
    int32   LockID;  // 23
};

// DeathThudLookups -- 5 cols, record_size 20, build 3.3.5.12340. INERT reference (not loaded).
struct DeathThudLookupsEntry
{
    int32   ID;  // 0
    int32   SizeClass;  // 1
    int32   TerrainTypeSoundID;  // 2
    int32   SoundEntryID;  // 3
    int32   SoundEntryIDWater;  // 4
};

// DeclinedWord -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct DeclinedWordEntry
{
    int32   ID;  // 0
    char*   Word;  // 1
};

// DeclinedWordCases -- 4 cols, record_size 16, build 3.3.5.12340. INERT reference (not loaded).
struct DeclinedWordCasesEntry
{
    int32   ID;  // 0
    int32   DeclinedWordID;  // 1
    int32   CaseIndex;  // 2
    char*   DeclinedWord;  // 3
};

// DungeonMap -- 8 cols, record_size 32, build 3.3.5.12340. INERT reference (not loaded).
struct DungeonMapEntry
{
    int32   ID;  // 0
    int32   MapID;  // 1
    int32   FloorIndex;  // 2
    float   MinX;  // 3
    float   MaxX;  // 4
    float   MinY;  // 5
    float   MaxY;  // 6
    int32   ParentWorldMapID;  // 7
};

// DungeonMapChunk -- 5 cols, record_size 20, build 3.3.5.12340. INERT reference (not loaded).
struct DungeonMapChunkEntry
{
    uint32  ID;  // [dbd-only] 0
    uint32  MapID;  // 1
    uint32  WMOGroupID;  // 2
    uint32  DungeonMapID;  // 3
    float   MinZ;  // 4
};

// EmotesTextData -- 18 cols, record_size 72, build 3.3.5.12340. INERT reference (not loaded).
struct EmotesTextDataEntry
{
    uint32  ID;  // 0
    char*   Text_lang[16];  // [dbd-only] 1-16
// uint32  Text_lang_flags;  // 17
};

// EmotesTextSound -- 5 cols, record_size 20, build 3.3.5.12340. INERT reference (not loaded).
struct EmotesTextSoundEntry
{
    uint32  ID;  // 0
    uint32  EmotesTextID;  // 1
    uint32  RaceID;  // 2
    uint32  SexID;  // 3
    uint32  SoundID;  // 4
};

// EnvironmentalDamage -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct EnvironmentalDamageEntry
{
    uint32  ID;  // 0
    uint32  EnumID;  // 1
    uint32  VisualkitID;  // 2
};

// Exhaustion -- 23 cols, record_size 92, build 3.3.5.12340. INERT reference (not loaded).
struct ExhaustionEntry
{
    uint32  ID;  // 0
    int32   Xp;  // 1
    float   Factor;  // 2
    float   OutdoorHours;  // 3
    float   InnHours;  // 4
    char*   Name_lang[16];  // 5-20
// uint32  Name_lang_flags;  // 21
    float   Threshold;  // 22
};

// FactionGroup -- 20 cols, record_size 80, build 3.3.5.12340. INERT reference (not loaded).
struct FactionGroupEntry
{
    uint32  ID;  // 0
    uint32  MaskID;  // 1
    char*   InternalName;  // 2
    char*   Name_lang[16];  // 3-18
// uint32  Name_lang_flags;  // 19
};

// FileData -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct FileDataEntry
{
    uint32  ID;  // 0
    char*   Filename;  // 1
    char*   Filepath;  // 2
};

// FootprintTextures -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct FootprintTexturesEntry
{
    int32   ID;  // 0
    char*   FootstepFilename;  // 1
};

// FootstepTerrainLookup -- 5 cols, record_size 20, build 3.3.5.12340. INERT reference (not loaded).
struct FootstepTerrainLookupEntry
{
    uint32  ID;  // 0
    uint32  CreatureFootstepID;  // 1
    uint32  TerrainSoundID;  // 2
    uint32  SoundID;  // 3
    uint32  SoundIDSplash;  // 4
};

// GMSurveyAnswers -- 20 cols, record_size 80, build 3.3.5.12340. INERT reference (not loaded).
struct GMSurveyAnswersEntry
{
    uint32  ID;  // 0
    uint32  Sort_Index;  // 1
    uint32  GMSurveyQuestionID;  // 2
    char*   Answer_lang[16];  // 3-18
// uint32  Answer_lang_flags;  // 19
};

// GMSurveyCurrentSurvey -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct GMSurveyCurrentSurveyEntry
{
    uint32  LANGID;  // 0
    uint32  GMSURVEY_ID;  // 1
};

// GMSurveyQuestions -- 18 cols, record_size 72, build 3.3.5.12340. INERT reference (not loaded).
struct GMSurveyQuestionsEntry
{
    uint32  ID;  // 0
    char*   Question_lang[16];  // 1-16
// uint32  Question_lang_flags;  // 17
};

// GMSurveySurveys -- 11 cols, record_size 44, build 3.3.5.12340. INERT reference (not loaded).
struct GMSurveySurveysEntry
{
    uint32  ID;  // 0
    uint32  Q[10];  // 1-10
};

// GMTicketCategory -- 18 cols, record_size 72, build 3.3.5.12340. INERT reference (not loaded).
struct GMTicketCategoryEntry
{
    uint32  ID;  // 0
    char*   Category_lang[16];  // 1-16
// uint32  Category_lang_flags;  // 17
};

// GameObjectArtKit -- 8 cols, record_size 32, build 3.3.5.12340. INERT reference (not loaded).
struct GameObjectArtKitEntry
{
    uint32  ID;  // 0
    char*   TextureVariation[3];  // 1-3
    char*   AttachModel[4];  // 4-7
};

// GameTables -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct GameTablesEntry
{
    char*   Name;  // 0
    int32   NumRows;  // 1
    int32   NumColumns;  // 2
};

// GameTips -- 18 cols, record_size 72, build 3.3.5.12340. INERT reference (not loaded).
struct GameTipsEntry
{
    uint32  ID;  // 0
    char*   Text_lang[16];  // 1-16
// uint32  Text_lang_flags;  // 17
};

// GroundEffectDoodad -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct GroundEffectDoodadEntry
{
    uint32  ID;  // [dbd-only] 0
    char*   Doodadpath;  // 1
    uint32  Flags;  // 2
};

// GroundEffectTexture -- 11 cols, record_size 44, build 3.3.5.12340. INERT reference (not loaded).
struct GroundEffectTextureEntry
{
    int32   ID;  // 0
    int32   DoodadID[4];  // 1-4
    int32   DoodadWeight[4];  // 5-8
    int32   Density;  // 9
    int32   Sound;  // 10
};

// HelmetGeosetVisData -- 8 cols, record_size 32, build 3.3.5.12340. INERT reference (not loaded).
struct HelmetGeosetVisDataEntry
{
    int32   ID;  // 0
    int32   HideGeoset[7];  // 1-7
};

// HolidayDescriptions -- 18 cols, record_size 72, build 3.3.5.12340. INERT reference (not loaded).
struct HolidayDescriptionsEntry
{
    uint32  ID;  // 0
    char*   Description_lang[16];  // 1-16
// uint32  Description_lang_flags;  // 17
};

// ItemCondExtCosts -- 4 cols, record_size 16, build 3.3.5.12340. INERT reference (not loaded). [phantom: commented fmt in DBCfmt.h]
struct ItemCondExtCostsEntry
{
    uint32  ID;  // 0
    uint32  CondExtendedCost;  // 1
    uint32  ItemExtendedCostEntry;  // 2
    uint32  ArenaSeason;  // 3
};

// ItemGroupSounds -- 5 cols, record_size 20, build 3.3.5.12340. INERT reference (not loaded).
struct ItemGroupSoundsEntry
{
    int32   ID;  // 0
    int32   Sound[4];  // 1-4
};

// ItemPetFood -- 18 cols, record_size 72, build 3.3.5.12340. INERT reference (not loaded).
struct ItemPetFoodEntry
{
    uint32  ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
};

// ItemPurchaseGroup -- 26 cols, record_size 104, build 3.3.5.12340. INERT reference (not loaded).
struct ItemPurchaseGroupEntry
{
    int32   ID;  // 0
    int32   ItemID[8];  // 1-8
    char*   Name_lang[16];  // 9-24
// uint32  Name_lang_flags;  // 25
};

// ItemSubClass -- 44 cols, record_size 176, build 3.3.5.12340. INERT reference (not loaded).
struct ItemSubClassEntry
{
    int32   ClassID;  // 0
    int32   SubClassID;  // 1
    int32   PrerequisiteProficiency;  // 2
    int32   PostrequisiteProficiency;  // 3
    int32   Flags;  // 4
    int32   DisplayFlags;  // 5
    int32   WeaponParrySeq;  // 6
    int32   WeaponReadySeq;  // 7
    int32   WeaponAttackSeq;  // 8
    int32   WeaponSwingSize;  // 9
    char*   DisplayName_lang[16];  // 10-25
// uint32  DisplayName_lang_flags;  // 26
    char*   VerboseName_lang[16];  // 27-42
// uint32  VerboseName_lang_flags;  // 43
};

// ItemSubClassMask -- 19 cols, record_size 76, build 3.3.5.12340. INERT reference (not loaded).
struct ItemSubClassMaskEntry
{
    int32   ClassID;  // 0
    int32   Mask;  // 1
    char*   Name_lang[16];  // 2-17
// uint32  Name_lang_flags;  // 18
};

// ItemVisualEffects -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct ItemVisualEffectsEntry
{
    uint32  ID;  // 0
    char*   Model;  // 1
};

// ItemVisuals -- 6 cols, record_size 24, build 3.3.5.12340. INERT reference (not loaded).
struct ItemVisualsEntry
{
    int32   ID;  // 0
    int32   Slot[5];  // 1-5
};

// LFGDungeonExpansion -- 8 cols, record_size 32, build 3.3.5.12340. INERT reference (not loaded).
struct LFGDungeonExpansionEntry
{
    uint32  ID;  // 0
    uint32  Lfg_ID;  // 1
    uint32  Expansion_level;  // 2
    uint32  Random_ID;  // 3
    uint32  Hard_level_min;  // 4
    uint32  Hard_level_max;  // 5
    uint32  Target_level_min;  // 6
    uint32  Target_level_max;  // 7
};

// LFGDungeonGroup -- 21 cols, record_size 84, build 3.3.5.12340. INERT reference (not loaded).
struct LFGDungeonGroupEntry
{
    uint32  ID;  // [dbd-only] 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
    int32   Order_index;  // 18
    int32   Parent_group_ID;  // 19
    int32   TypeID;  // 20
};

// LanguageWords -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct LanguageWordsEntry
{
    uint32  ID;  // 0
    uint32  LanguageID;  // 1
    char*   Word;  // 2
};

// Languages -- 18 cols, record_size 72, build 3.3.5.12340. INERT reference (not loaded).
struct LanguagesEntry
{
    int32   ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
};

// Light -- 15 cols, record_size 60, build 3.3.5.12340. INERT reference (not loaded).
struct LightEntry
{
    uint32  ID;  // 0
    uint32  ContinentID;  // 1
    float   GameCoords[3];  // 2-4
    float   GameFalloffStart;  // 5
    float   GameFalloffEnd;  // 6
    uint32  LightParamsID[8];  // 7-14
};

// LightFloatBand -- 34 cols, record_size 136, build 3.3.5.12340. INERT reference (not loaded).
struct LightFloatBandEntry
{
    int32   ID;  // 0
    int32   Num;  // 1
    int32   Time[16];  // 2-17
    float   Data[16];  // 18-33
};

// LightIntBand -- 34 cols, record_size 136, build 3.3.5.12340. INERT reference (not loaded).
struct LightIntBandEntry
{
    uint32  ID;  // 0
    uint32  Num;  // 1
    uint32  Time[16];  // 2-17
    uint32  Data[16];  // 18-33
};

// LightParams -- 9 cols, record_size 36, build 3.3.5.12340. INERT reference (not loaded).
struct LightParamsEntry
{
    uint32  ID;  // 0
    int32   HighlightSky;  // 1
    uint32  LightSkyboxID;  // 2
    uint32  CloudTypeID;  // [dbd-only] 3
    float   Glow;  // 4
    float   WaterShallowAlpha;  // 5
    float   WaterDeepAlpha;  // 6
    float   OceanShallowAlpha;  // 7
    float   OceanDeepAlpha;  // 8
};

// LightSkybox -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct LightSkyboxEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    uint32  Flags;  // 2
};

// LiquidMaterial -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct LiquidMaterialEntry
{
    uint32  ID;  // 0
    uint32  LVF;  // 1
    uint32  Flags;  // 2
};

// LoadingScreenTaxiSplines -- 19 cols, record_size 76, build 3.3.5.12340. INERT reference (not loaded).
struct LoadingScreenTaxiSplinesEntry
{
    int32   ID;  // 0
    int32   PathID;  // 1
    float   Locx[8];  // 2-9
    float   Locy[8];  // 10-17
    int32   LegIndex;  // 18
};

// LoadingScreens -- 4 cols, record_size 16, build 3.3.5.12340. INERT reference (not loaded).
struct LoadingScreensEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    char*   FileName;  // 2
    uint32  HasWideScreen;  // 3
};

// LockType -- 53 cols, record_size 212, build 3.3.5.12340. INERT reference (not loaded).
struct LockTypeEntry
{
    uint32  ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
    char*   ResourceName_lang[16];  // 18-33
// uint32  ResourceName_lang_flags;  // 34
    char*   Verb_lang[16];  // 35-50
// uint32  Verb_lang_flags;  // 51
    char*   CursorName;  // 52
};

// Material -- 5 cols, record_size 20, build 3.3.5.12340. INERT reference (not loaded).
struct MaterialEntry
{
    int32   ID;  // 0
    int32   Flags;  // 1
    int32   FoleySoundID;  // 2
    int32   SheatheSoundID;  // 3
    int32   UnsheatheSoundID;  // 4
};

// MovieFileData -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct MovieFileDataEntry
{
    uint32  FileDataID;  // 0
    uint32  Resolution;  // 1
};

// MovieVariation -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct MovieVariationEntry
{
    uint32  ID;  // 0
    uint32  MovieID;  // 1
    uint32  FileDataID;  // 2
};

// NPCSounds -- 5 cols, record_size 20, build 3.3.5.12340. INERT reference (not loaded).
struct NPCSoundsEntry
{
    uint32  ID;  // 0
    uint32  SoundID[4];  // 1-4
};

// NameGen -- 4 cols, record_size 16, build 3.3.5.12340. INERT reference (not loaded).
struct NameGenEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    uint32  RaceID;  // 2
    uint32  Sex;  // 3
};

// NamesProfanity -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct NamesProfanityEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    int32   Language;  // 2
};

// NamesReserved -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct NamesReservedEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    int32   Language;  // 2
};

// ObjectEffect -- 12 cols, record_size 48, build 3.3.5.12340. INERT reference (not loaded).
struct ObjectEffectEntry
{
    int32   ID;  // 0
    char*   Name;  // 1
    int32   ObjectEffectGroupID;  // 2
    int32   TriggerType;  // 3
    int32   EventType;  // 4
    int32   EffectRecType;  // 5
    int32   EffectRecID;  // 6
    int32   Attachment;  // 7
    float   Offset[3];  // 8-10
    int32   ObjectEffectModifierID;  // 11
};

// ObjectEffectGroup -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct ObjectEffectGroupEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
};

// ObjectEffectModifier -- 8 cols, record_size 32, build 3.3.5.12340. INERT reference (not loaded).
struct ObjectEffectModifierEntry
{
    uint32  ID;  // 0
    int32   InputType;  // 1
    int32   MapType;  // 2
    int32   OutputType;  // 3
    float   Param[4];  // 4-7
};

// ObjectEffectPackage -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct ObjectEffectPackageEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
};

// ObjectEffectPackageElem -- 4 cols, record_size 16, build 3.3.5.12340. INERT reference (not loaded).
struct ObjectEffectPackageElemEntry
{
    uint32  ID;  // 0
    uint32  ObjectEffectPackageID;  // 1
    uint32  ObjectEffectGroupID;  // 2
    int32   StateType;  // 3
};

// Package -- 20 cols, record_size 80, build 3.3.5.12340. INERT reference (not loaded).
struct PackageEntry
{
    uint32  ID;  // 0
    char*   Icon;  // 1
    int32   Cost;  // 2
    char*   Name_lang[16];  // 3-18
// uint32  Name_lang_flags;  // 19
};

// PageTextMaterial -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct PageTextMaterialEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
};

// PaperDollItemFrame -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct PaperDollItemFrameEntry
{
    char*   ItemButtonName;  // 0
    char*   SlotIcon;  // 1
    int32   SlotNumber;  // 2
};

// ParticleColor -- 10 cols, record_size 40, build 3.3.5.12340. INERT reference (not loaded).
struct ParticleColorEntry
{
    uint32  ID;  // 0
    int32   Start[3];  // 1-3
    int32   Mid[3];  // 4-6
    int32   End[3];  // 7-9
};

// PetPersonality -- 24 cols, record_size 96, build 3.3.5.12340. INERT reference (not loaded).
struct PetPersonalityEntry
{
    uint32  ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
    int32   HappinessThreshold[3];  // 18-20
    float   HappinessDamage[3];  // 21-23
};

// PetitionType -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct PetitionTypeEntry
{
    uint32  ID;  // [dbd-only] 0
    char*   Name;  // [dbd-only] 1
    int32   Type;  // [dbd-only] 2
};

// QuestInfo -- 18 cols, record_size 72, build 3.3.5.12340. INERT reference (not loaded).
struct QuestInfoEntry
{
    uint32  ID;  // 0
    char*   InfoName_lang[16];  // 1-16
// uint32  InfoName_lang_flags;  // 17
};

// Resistances -- 20 cols, record_size 80, build 3.3.5.12340. INERT reference (not loaded).
struct ResistancesEntry
{
    uint32  ID;  // 0
    uint32  Flags;  // 1
    uint32  FizzleSoundID;  // 2
    char*   Name_lang[16];  // 3-18
// uint32  Name_lang_flags;  // 19
};

// ScreenEffect -- 10 cols, record_size 40, build 3.3.5.12340. INERT reference (not loaded).
struct ScreenEffectEntry
{
    int32   ID;  // 0
    char*   Name;  // 1
    int32   Effect;  // 2
    int32   Param[4];  // 3-6
    int32   LightParamsID;  // 7
    int32   SoundAmbienceID;  // 8
    int32   ZoneMusicID;  // 9
};

// ServerMessages -- 18 cols, record_size 72, build 3.3.5.12340. INERT reference (not loaded).
struct ServerMessagesEntry
{
    uint32  ID;  // 0
    char*   Text_lang[16];  // 1-16
// uint32  Text_lang_flags;  // 17
};

// SheatheSoundLookups -- 7 cols, record_size 28, build 3.3.5.12340. INERT reference (not loaded).
struct SheatheSoundLookupsEntry
{
    uint32  ID;  // 0
    uint32  ClassID;  // 1
    uint32  SubclassID;  // 2
    uint32  Material;  // [dbd-only] 3
    uint32  CheckMaterial;  // [dbd-only] 4
    uint32  SheatheSound;  // 5
    uint32  UnsheatheSound;  // 6
};

// SkillCostsData -- 5 cols, record_size 20, build 3.3.5.12340. INERT reference (not loaded).
struct SkillCostsDataEntry
{
    uint32  ID;  // 0
    uint32  SkillCostsID;  // 1
    uint32  Cost[3];  // 2-4
};

// SkillLineCategory -- 19 cols, record_size 76, build 3.3.5.12340. INERT reference (not loaded).
struct SkillLineCategoryEntry
{
    uint32  ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
    uint32  SortIndex;  // 18
};

// SkillTiers -- 33 cols, record_size 132, build 3.3.5.12340. INERT reference (not loaded).
struct SkillTiersEntry
{
    uint32  ID;  // 0
    uint32  Cost[16];  // 1-16
    uint32  Value[16];  // 17-32
};

// SoundAmbience -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct SoundAmbienceEntry
{
    int32   ID;  // 0
    int32   AmbienceID[2];  // 1-2
};

// SoundEmitters -- 10 cols, record_size 40, build 3.3.5.12340. INERT reference (not loaded).
struct SoundEmittersEntry
{
    uint32  ID;  // 0
    float   Position[3];  // 1-3
    float   Direction[3];  // 4-6
    int32   SoundEntryAdvancedID;  // 7
    int32   MapID;  // 8
    char*   Name;  // 9
};

// SoundEntriesAdvanced -- 24 cols, record_size 96, build 3.3.5.12340. INERT reference (not loaded).
struct SoundEntriesAdvancedEntry
{
    int32   ID;  // 0
    int32   SoundEntryID;  // 1
    float   InnerRadius2D;  // 2
    int32   TimeA;  // 3
    int32   TimeB;  // 4
    int32   TimeC;  // 5
    int32   TimeD;  // 6
    int32   RandomOffsetRange;  // 7
    int32   Usage;  // 8
    int32   TimeIntervalMin;  // 9
    int32   TimeIntervalMax;  // 10
    int32   VolumeSliderCategory;  // 11
    float   DuckToSFX;  // 12
    float   DuckToMusic;  // 13
    float   DuckToAmbience;  // 14
    float   InnerRadiusOfInfluence;  // 15
    float   OuterRadiusOfInfluence;  // 16
    int32   TimeToDuck;  // 17
    int32   TimeToUnduck;  // 18
    float   InsideAngle;  // 19
    float   OutsideAngle;  // 20
    float   OutsideVolume;  // 21
    float   OuterRadius2D;  // 22
    char*   Name;  // 23
};

// SoundFilter -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct SoundFilterEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
};

// SoundFilterElem -- 13 cols, record_size 52, build 3.3.5.12340. INERT reference (not loaded).
struct SoundFilterElemEntry
{
    uint32  ID;  // 0
    uint32  SoundFilterID;  // 1
    uint32  OrderIndex;  // 2
    int32   FilterType;  // 3
    float   Params[9];  // 4-12
};

// SoundProviderPreferences -- 24 cols, record_size 96, build 3.3.5.12340. INERT reference (not loaded).
struct SoundProviderPreferencesEntry
{
    uint32  ID;  // 0
    char*   Description;  // 1
    uint32  Flags;  // 2
    int32   EAXEnvironmentSelection;  // 3
    float   EAXDecayTime;  // 4
    float   EAX2EnvironmentSize;  // 5
    float   EAX2EnvironmentDiffusion;  // 6
    int32   EAX2Room;  // 7
    int32   EAX2RoomHF;  // 8
    float   EAX2DecayHFRatio;  // 9
    int32   EAX2Reflections;  // 10
    float   EAX2ReflectionsDelay;  // 11
    int32   EAX2Reverb;  // 12
    float   EAX2ReverbDelay;  // 13
    float   EAX2RoomRolloff;  // 14
    float   EAX2AirAbsorption;  // 15
    int32   EAX3RoomLF;  // [dbd-only] 16
    float   EAX3DecayLFRatio;  // 17
    float   EAX3EchoTime;  // 18
    float   EAX3EchoDepth;  // 19
    float   EAX3ModulationTime;  // 20
    float   EAX3ModulationDepth;  // 21
    float   EAX3HFReference;  // 22
    float   EAX3LFReference;  // 23
};

// SoundSamplePreferences -- 17 cols, record_size 68, build 3.3.5.12340. INERT reference (not loaded).
struct SoundSamplePreferencesEntry
{
    uint32  ID;  // 0
    int32   Field_0_6_0_3592_001;  // 1
    int32   Field_0_6_0_3592_002;  // [dbd-only] 2
    int32   EAX2SampleRoom;  // 3
    int32   Field_0_6_0_3592_004;  // [dbd-only] 4
    int32   Field_0_6_0_3592_005;  // [dbd-only] 5
    float   Field_0_6_0_3592_006;  // 6
    int32   Field_0_6_0_3592_007;  // [dbd-only] 7
    float   EAX2SampleOcclusionLFRatio;  // 8
    float   EAX2SampleOcclusionRoomRatio;  // 9
    int32   Field_0_6_0_3592_010;  // [dbd-only] 10
    float   EAX1EffectLevel;  // 11
    int32   Field_0_6_0_3592_012;  // [dbd-only] 12
    float   Field_0_6_0_3592_013;  // 13
    float   EAX3SampleExclusion;  // 14
    float   Field_0_6_0_3592_015;  // 15
    int32   Field_0_6_0_3592_016;  // [dbd-only] 16
};

// SoundWaterType -- 4 cols, record_size 16, build 3.3.5.12340. INERT reference (not loaded).
struct SoundWaterTypeEntry
{
    uint32  ID;  // 0
    int32   SoundType;  // 1
    int32   SoundSubtype;  // 2
    uint32  SoundID;  // 3
};

// SpamMessages -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct SpamMessagesEntry
{
    int32   ID;  // 0
    char*   Text;  // 1
};

// SpellCategory -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct SpellCategoryEntry
{
    uint32  ID;  // 0
    uint32  Flags;  // 1
};

// SpellChainEffects -- 48 cols, record_size 177, build 3.3.5.12340. INERT reference (not loaded).
struct SpellChainEffectsEntry
{
    int32   ID;  // 0
    float   AvgSegLen;  // 1
    float   Width;  // 2
    float   NoiseScale;  // 3
    float   TexCoordScale;  // 4
    int32   SegDuration;  // 5
    int32   SegDelay;  // 6
    char*   Texture;  // 7
    int32   Flags;  // 8
    int32   JointCount;  // 9
    float   JointOffsetRadius;  // 10
    int32   JointsPerMinorJoint;  // 11
    int32   MinorJointsPerMajorJoint;  // 12
    float   MinorJointScale;  // 13
    float   MajorJointScale;  // 14
    float   JointMoveSpeed;  // 15
    float   JointSmoothness;  // 16
    float   MinDurationBetweenJointJumps;  // 17
    float   MaxDurationBetweenJointJumps;  // 18
    float   WaveHeight;  // 19
    float   WaveFreq;  // 20
    float   WaveSpeed;  // 21
    float   MinWaveAngle;  // 22
    float   MaxWaveAngle;  // 23
    float   MinWaveSpin;  // 24
    float   MaxWaveSpin;  // 25
    float   ArcHeight;  // 26
    float   MinArcAngle;  // 27
    float   MaxArcAngle;  // 28
    float   MinArcSpin;  // 29
    float   MaxArcSpin;  // 30
    float   DelayBetweenEffects;  // 31
    float   MinFlickerOnDuration;  // 32
    float   MaxFlickerOnDuration;  // 33
    float   MinFlickerOffDuration;  // 34
    float   MaxFlickerOffDuration;  // 35
    float   PulseSpeed;  // 36
    float   PulseOnLength;  // 37
    float   PulseFadeLength;  // 38
    uint8   Alpha;  // [dbd-only] 39
    uint8   Red;  // [dbd-only] 40
    uint8   Green;  // [dbd-only] 41
    uint8   Blue;  // [dbd-only] 42
    uint8   BlendMode;  // [dbd-only] 43
    char*   Combo;  // 44
    int32   RenderLayer;  // 45
    float   TextureLength;  // 46
    float   WavePhase;  // 47
};

// SpellDescriptionVariables -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct SpellDescriptionVariablesEntry
{
    int32   ID;  // 0
    char*   Variables;  // 1
};

// SpellDispelType -- 21 cols, record_size 84, build 3.3.5.12340. INERT reference (not loaded).
struct SpellDispelTypeEntry
{
    uint32  ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
    uint32  Mask;  // 18
    int32   ImmunityPossible;  // 19
    char*   InternalName;  // 20
};

// SpellEffectCameraShakes -- 4 cols, record_size 16, build 3.3.5.12340. INERT reference (not loaded).
struct SpellEffectCameraShakesEntry
{
    uint32  ID;  // 0
    uint32  CameraShake[3];  // 1-3
};

// SpellIcon -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct SpellIconEntry
{
    uint32  ID;  // 0
    char*   TextureFilename;  // 1
};

// SpellMechanic -- 18 cols, record_size 72, build 3.3.5.12340. INERT reference (not loaded).
struct SpellMechanicEntry
{
    uint32  ID;  // 0
    char*   StateName_lang[16];  // 1-16
// uint32  StateName_lang_flags;  // 17
};

// SpellMissile -- 15 cols, record_size 60, build 3.3.5.12340. INERT reference (not loaded).
struct SpellMissileEntry
{
    int32   ID;  // 0
    int32   Flags;  // 1
    float   DefaultPitchMin;  // 2
    float   DefaultPitchMax;  // 3
    float   DefaultSpeedMin;  // 4
    float   DefaultSpeedMax;  // 5
    float   RandomizeFacingMin;  // 6
    float   RandomizeFacingMax;  // 7
    float   RandomizePitchMin;  // 8
    float   RandomizePitchMax;  // 9
    float   RandomizeSpeedMin;  // 10
    float   RandomizeSpeedMax;  // 11
    float   Gravity;  // 12
    float   MaxDuration;  // 13
    float   CollisionRadius;  // 14
};

// SpellMissileMotion -- 5 cols, record_size 20, build 3.3.5.12340. INERT reference (not loaded).
struct SpellMissileMotionEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    char*   ScriptBody;  // 2
    uint32  Flags;  // 3
    int32   MissileCount;  // 4
};

// SpellVisual -- 32 cols, record_size 128, build 3.3.5.12340. INERT reference (not loaded).
struct SpellVisualEntry
{
    uint32  ID;  // 0
    uint32  PrecastKit;  // 1
    uint32  CastKit;  // 2
    uint32  ImpactKit;  // 3
    uint32  StateKit;  // 4
    uint32  StateDoneKit;  // 5
    uint32  ChannelKit;  // 6
    uint32  HasMissile;  // 7
    int32   MissileModel;  // 8
    uint32  MissilePathType;  // 9
    uint32  MissileDestinationAttachment;  // 10
    uint32  MissileSound;  // 11
    uint32  AnimEventSoundID;  // 12
    uint32  Flags;  // 13
    uint32  CasterImpactKit;  // 14
    uint32  TargetImpactKit;  // 15
    int32   MissileAttachment;  // 16
    uint32  MissileFollowGroundHeight;  // 17
    uint32  MissileFollowGroundDropSpeed;  // 18
    uint32  MissileFollowGroundApproach;  // 19
    uint32  MissileFollowGroundFlags;  // 20
    uint32  MissileMotion;  // 21
    uint32  MissileTargetingKit;  // 22
    uint32  InstantAreaKit;  // 23
    uint32  ImpactAreaKit;  // 24
    uint32  PersistentAreaKit;  // 25
    float   MissileCastOffset[3];  // 26-28
    float   MissileImpactOffset[3];  // 29-31
};

// SpellVisualEffectName -- 7 cols, record_size 28, build 3.3.5.12340. INERT reference (not loaded).
struct SpellVisualEffectNameEntry
{
    uint32  ID;  // [dbd-only] 0
    char*   Name;  // 1
    char*   FileName;  // 2
    float   AreaEffectSize;  // 3
    float   Scale;  // 4
    float   MinAllowedScale;  // 5
    float   MaxAllowedScale;  // 6
};

// SpellVisualKit -- 38 cols, record_size 152, build 3.3.5.12340. INERT reference (not loaded).
struct SpellVisualKitEntry
{
    int32   ID;  // 0
    int32   StartAnimID;  // 1
    int32   AnimID;  // 2
    int32   HeadEffect;  // 3
    int32   ChestEffect;  // 4
    int32   BaseEffect;  // 5
    int32   LeftHandEffect;  // 6
    int32   RightHandEffect;  // 7
    int32   BreathEffect;  // 8
    int32   LeftWeaponEffect;  // 9
    int32   RightWeaponEffect;  // 10
    int32   SpecialEffect[3];  // 11-13
    int32   WorldEffect;  // 14
    int32   SoundID;  // 15
    int32   ShakeID;  // 16
    int32   CharProc[4];  // 17-20
    float   CharParamZero[4];  // [dbd-only] 21-24
    float   CharParamOne[4];  // [dbd-only] 25-28
    float   CharParamTwo[4];  // [dbd-only] 29-32
    float   CharParamThree[4];  // [dbd-only] 33-36
    int32   Flags;  // 37
};

// SpellVisualKitAreaModel -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct SpellVisualKitAreaModelEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    uint32  EnumID;  // 2
};

// SpellVisualKitModelAttach -- 10 cols, record_size 40, build 3.3.5.12340. INERT reference (not loaded).
struct SpellVisualKitModelAttachEntry
{
    int32   ID;  // 0
    int32   ParentSpellVisualKitID;  // 1
    int32   SpellVisualEffectNameID;  // 2
    int32   AttachmentID;  // 3
    float   Offset[3];  // 4-6
    float   Yaw;  // [dbd-only] 7
    float   Pitch;  // 8
    float   Roll;  // [dbd-only] 9
};

// SpellVisualPrecastTransitions -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct SpellVisualPrecastTransitionsEntry
{
    uint32  ID;  // [dbd-only] 0
    char*   PrecastLoadAnimName;  // [dbd-only] 1
    char*   PrecastHoldAnimName;  // [dbd-only] 2
};

// Startup_Strings -- 19 cols, record_size 76, build 3.3.5.12340. INERT reference (not loaded).
struct Startup_StringsEntry
{
    int32   ID;  // 0
    char*   Name;  // 1
    char*   Message_lang[16];  // 2-17
// uint32  Message_lang_flags;  // 18
};

// Stationery -- 4 cols, record_size 16, build 3.3.5.12340. INERT reference (not loaded).
struct StationeryEntry
{
    uint32  ID;  // 0
    uint32  ItemID;  // 1
    char*   Texture;  // 2
    uint32  Flags;  // 3
};

// StringLookups -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct StringLookupsEntry
{
    uint32  ID;  // 0
    char*   String;  // 1
};

// TerrainType -- 6 cols, record_size 24, build 3.3.5.12340. INERT reference (not loaded).
struct TerrainTypeEntry
{
    int32   TerrainID;  // 0
    char*   TerrainDesc;  // 1
    int32   FootstepSprayRun;  // 2
    int32   FootstepSprayWalk;  // 3
    int32   SoundID;  // 4
    int32   Flags;  // 5
};

// TerrainTypeSounds -- 1 cols, record_size 4, build 3.3.5.12340. INERT reference (not loaded).
struct TerrainTypeSoundsEntry
{
    uint32  ID;  // 0
};

// TransportAnimation -- 7 cols, record_size 28, build 3.3.5.12340. INERT reference (not loaded).
struct TransportAnimationEntry
{
    uint32  ID;  // 0
    uint32  TransportID;  // 1
    uint32  TimeIndex;  // 2
    float   Pos[3];  // 3-5
    uint32  SequenceID;  // 6
};

// TransportPhysics -- 11 cols, record_size 44, build 3.3.5.12340. INERT reference (not loaded).
struct TransportPhysicsEntry
{
    uint32  ID;  // 0
    float   WaveAmp;  // 1
    float   WaveTimeScale;  // 2
    float   RollAmp;  // 3
    float   RollTimeScale;  // 4
    float   PitchAmp;  // 5
    float   PitchTimeScale;  // 6
    float   MaxBank;  // 7
    float   MaxBankTurnSpeed;  // 8
    float   SpeedDampThresh;  // 9
    float   SpeedDamp;  // 10
};

// TransportRotation -- 7 cols, record_size 28, build 3.3.5.12340. INERT reference (not loaded).
struct TransportRotationEntry
{
    uint32  ID;  // 0
    uint32  GameObjectsID;  // 1
    uint32  TimeIndex;  // 2
    float   RotX;  // 3
    float   RotY;  // 4
    float   RotZ;  // 5
    float   RotW;  // 6
};

// UISoundLookups -- 3 cols, record_size 12, build 3.3.5.12340. INERT reference (not loaded).
struct UISoundLookupsEntry
{
    uint32  ID;  // 0
    uint32  SoundID;  // 1
    char*   SoundName;  // 2
};

// UnitBlood -- 10 cols, record_size 40, build 3.3.5.12340. INERT reference (not loaded).
struct UnitBloodEntry
{
    int32   ID;  // 0
    int32   CombatBloodSpurtFront[2];  // 1-2
    int32   CombatBloodSpurtBack[2];  // 3-4
    char*   GroundBlood[5];  // 5-9
};

// UnitBloodLevels -- 4 cols, record_size 16, build 3.3.5.12340. INERT reference (not loaded).
struct UnitBloodLevelsEntry
{
    uint32  ID;  // 0
    int32   Violencelevel[3];  // 1-3
};

// VehicleUIIndSeat -- 5 cols, record_size 20, build 3.3.5.12340. INERT reference (not loaded).
struct VehicleUIIndSeatEntry
{
    int32   ID;  // 0
    int32   VehicleUIIndicatorID;  // 1
    int32   VirtualSeatIndex;  // 2
    float   XPos;  // 3
    float   YPos;  // 4
};

// VehicleUIIndicator -- 2 cols, record_size 8, build 3.3.5.12340. INERT reference (not loaded).
struct VehicleUIIndicatorEntry
{
    uint32  ID;  // [dbd-only] 0
    char*   BackgroundTexture;  // 1
};

// VideoHardware -- 23 cols, record_size 92, build 3.3.5.12340. INERT reference (not loaded).
struct VideoHardwareEntry
{
    int32   ID;  // 0
    int32   VendorID;  // 1
    int32   DeviceID;  // 2
    int32   FarclipIdx;  // 3
    int32   TerrainLODDistIdx;  // 4
    int32   TerrainShadowLOD;  // 5
    int32   DetailDoodadDensityIdx;  // 6
    int32   DetailDoodadAlpha;  // 7
    int32   AnimatingDoodadIdx;  // 8
    int32   Trilinear;  // 9
    int32   NumLights;  // 10
    int32   Specularity;  // 11
    int32   WaterLODIdx;  // 12
    int32   ParticleDensityIdx;  // 13
    int32   UnitDrawDistIdx;  // 14
    int32   SmallCullDistIdx;  // 15
    int32   ResolutionIdx;  // 16
    int32   BaseMipLevel;  // 17
    char*   OglOverrides;  // 18
    char*   D3dOverrides;  // 19
    int32   FixLag;  // 20
    int32   Multisample;  // 21
    int32   Atlasdisable;  // 22
};

// VocalUISounds -- 7 cols, record_size 28, build 3.3.5.12340. INERT reference (not loaded).
struct VocalUISoundsEntry
{
    int32   ID;  // 0
    int32   VocalUIEnum;  // 1
    int32   RaceID;  // 2
    int32   NormalSoundID[2];  // 3-4
    int32   PissedSoundID[2];  // 5-6
};

// WeaponImpactSounds -- 23 cols, record_size 92, build 3.3.5.12340. INERT reference (not loaded).
struct WeaponImpactSoundsEntry
{
    uint32  ID;  // 0
    uint32  WeaponSubClassID;  // 1
    uint32  ParrySoundType;  // 2
    uint32  ImpactSoundID[10];  // 3-12
    uint32  CritImpactSoundID[10];  // 13-22
};

// WeaponSwingSounds2 -- 4 cols, record_size 16, build 3.3.5.12340. INERT reference (not loaded).
struct WeaponSwingSounds2Entry
{
    int32   ID;  // 0
    int32   SwingType;  // 1
    int32   Crit;  // 2
    int32   SoundID;  // 3
};

// Weather -- 8 cols, record_size 32, build 3.3.5.12340. INERT reference (not loaded).
struct WeatherEntry
{
    int32   ID;  // 0
    int32   AmbienceID;  // 1
    int32   EffectType;  // 2
    float   TransitionSkyBox;  // 3
    float   EffectColor[3];  // 4-6
    char*   EffectTexture;  // 7
};

// WorldChunkSounds -- 9 cols, record_size 36, build 3.3.5.12340. INERT reference (not loaded).
struct WorldChunkSoundsEntry
{
    int32   ID;  // 0
    int32   ChunkX;  // 1
    int32   ChunkY;  // 2
    int32   SubchunkX;  // 3
    int32   SubchunkY;  // 4
    int32   ZoneIntroMusicID;  // 5
    int32   ZoneMusicID;  // 6
    int32   SoundAmbienceID;  // 7
    int32   SoundProviderPreferencesID;  // 8
};

// WorldMapContinent -- 14 cols, record_size 56, build 3.3.5.12340. INERT reference (not loaded).
struct WorldMapContinentEntry
{
    int32   ID;  // 0
    int32   MapID;  // 1
    int32   LeftBoundary;  // 2
    int32   RightBoundary;  // 3
    int32   TopBoundary;  // 4
    int32   BottomBoundary;  // 5
    float   ContinentOffsetX;  // 6
    float   ContinentOffsetY;  // 7
    float   Scale;  // 8
    float   TaxiMinX;  // 9
    float   TaxiMinY;  // 10
    float   TaxiMaxX;  // 11
    float   TaxiMaxY;  // 12
    int32   WorldMapID;  // 13
};

// WorldMapTransforms -- 10 cols, record_size 40, build 3.3.5.12340. INERT reference (not loaded).
struct WorldMapTransformsEntry
{
    uint32  ID;  // 0
    uint32  MapID;  // 1
    float   RegionMin[2];  // 2-3
    float   RegionMax[2];  // 4-5
    uint32  NewMapID;  // 6
    float   RegionOffset[2];  // 7-8
    uint32  NewDungeonMapID;  // 9
};

// WorldStateUI -- 63 cols, record_size 252, build 3.3.5.12340. INERT reference (not loaded).
struct WorldStateUIEntry
{
    int32   ID;  // 0
    int32   MapID;  // 1
    int32   AreaID;  // 2
    int32   PhaseShift;  // 3
    char*   Icon;  // 4
    char*   String_lang[16];  // 5-20
// uint32  String_lang_flags;  // 21
    char*   Tooltip_lang[16];  // 22-37
// uint32  Tooltip_lang_flags;  // 38
    int32   StateVariable;  // 39
    int32   Type;  // 40
    char*   DynamicIcon;  // 41
    char*   DynamicTooltip_lang[16];  // 42-57
// uint32  DynamicTooltip_lang_flags;  // 58
    char*   ExtendedUI;  // 59
    int32   ExtendedUIStateVariable[3];  // 60-62
};

// WorldStateZoneSounds -- 8 cols, record_size 32, build 3.3.5.12340. INERT reference (not loaded).
struct WorldStateZoneSoundsEntry
{
    uint32  WorldStateID;  // 0
    uint32  WorldStateValue;  // 1
    uint32  AreaID;  // 2
    uint32  WMOAreaID;  // 3
    uint32  ZoneIntroMusicID;  // 4
    uint32  ZoneMusicID;  // 5
    uint32  SoundAmbienceID;  // 6
    uint32  SoundProviderPreferencesID;  // 7
};

// WowError_Strings -- 19 cols, record_size 76, build 3.3.5.12340. INERT reference (not loaded).
struct WowError_StringsEntry
{
    int32   ID;  // 0
    char*   Name;  // 1
    char*   Description_lang[16];  // 2-17
// uint32  Description_lang_flags;  // 18
};

// ZoneIntroMusicTable -- 5 cols, record_size 20, build 3.3.5.12340. INERT reference (not loaded).
struct ZoneIntroMusicTableEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    uint32  SoundID;  // 2
    uint32  Priority;  // 3
    uint32  MinDelayMinutes;  // 4
};

// ZoneMusic -- 8 cols, record_size 32, build 3.3.5.12340. INERT reference (not loaded).
struct ZoneMusicEntry
{
    uint32  ID;  // 0
    char*   SetName;  // 1
    int32   SilenceIntervalMin[2];  // 2-3
    int32   SilenceIntervalMax[2];  // 4-5
    uint32  Sounds[2];  // 6-7
};

// gtNPCManaCostScaler -- 1 cols, record_size 4, build 3.3.5.12340. INERT reference (not loaded).
struct gtNPCManaCostScalerEntry
{
    float   Data;  // 0
};

// gtOCTRegenMP -- 1 cols, record_size 4, build 3.3.5.12340. INERT reference (not loaded). [phantom: commented fmt in DBCfmt.h]
struct gtOCTRegenMPEntry
{
    float   Data;  // 0
};

#endif
